README.md

Add group norms contribution by yuri

---

collaboration/communication.md

Edited communication.md to test merge conflict

---

collaboration/communication.md

commit to Communication doc

---

collaboration/README.md

Adding group norms template

---

collaboration/learning_goals.md

Adding a draft of the Learning Goals

---

collaboration/learning_goals.md

Wrote a brief bullet points about my Learning Goals.

Edited Learning Goals for Sukhrob Muborakshoev

---

collaboration/constraints.md

/**Update**\
Constrains
by: Dmytro Klymenko
Hey Team, I added constrains inside the .md file. In section Internal: Voluntary > Hours , I wrote (To be determined). We will need to discuss it at our meeting.

Constrains update

---

collaboration/communication.md

- Name: communication markdown review 
- By: olumide kolawole 
- Description:
Hey team,
I’ve put together a document to help us stay organized and keep communication clear. It includes:
- A weekly communication schedule so we all know when and how to check in.
- Details on what each communication channel is for (Slack, video calls, etc.).
- Everyone’s availability to make scheduling easier.
- A quick guide on when to ask for help and how to escalate if needed.
- Some reminders about sticking to our group norms and documenting as we go.

Communication markdown by  olumide kolawole

---

.gitignore
collaboration/guide/0_repository_setup.md
solutions/count_vowels.py
solutions/tests/test_count_vowels.py

Adding count_vowels task 1 and test_count_vowels

---

collaboration/communication.md

Please review and commit your time preferences in the file.

Edited the template for the communication.md file.

---

collaboration/communication.md

Khadija added her schedule and availability.

---

collaboration/communication.md

Trying to solve a markdown issue in communication.md

---

collaboration/communication.md

12/28/2024
by Dmytro Klymenko
Hi, updating my time availability.

communication Dmytro

---

collaboration/learning_goals.md

My own personal learning goals for this project

My personal learning goals

---

collaboration/communication.md

Henry schedule

---

README.md
collaboration/learning_goals.md
solutions/capitalize_character.py
solutions/tests/test_capitalize_character.py

Root readme khadija new

---

solutions/find_max_in_list.py
solutions/tests/test_find_max_in_list.py

Add find_max_in_list function with tests

---

.vscode/settings.json
collaboration/communication.md

change time in communication

---

solutions/capitalize_character.py
solutions/tests/test_capitalize_character.py

Minor _not final_ changes on the test file, Please check my draft

---

collaboration/learning_goals.md

Dmytro's learning goals

---

collaboration/communication.md

Communication yuri

---

solutions/sum_of_digits.py
solutions/tests/test_sum_of_digits.py

Add input validation and tests for sum_of_digits

---

collaboration/learning_goals.md

update learning goals document with refined objectives and tasks

---

README.md

adding README update

---

solutions/tests/test_even_numbers.py

Fixed Adding even_numbers and test_even_numbers branch

---

.vscode/settings.json
solutions/convert_fahrenheit_to_celsius.py
solutions/tests/test_convert_fahrenheit_to_celsius.py

Convert fahrenheit to celsius

---

solutions/add_two_numbers.py
solutions/tests/test_add_two_numbers.py

Adding add two numbers

---

solutions/is_palindrome.py
solutions/tests/test_is_palindrome.py

Adding is_palindrome and test_is_palindrome

---

solutions/count_character_occurences.py
solutions/count_character_occurrences.py
solutions/sum_odd_numbers.py
solutions/tests/test_count_character_occurrences.py
solutions/tests/test_sum_odd_numbers.py

Solution 2: Sum of odd numbers

---

solutions/count_character_occurences.py
solutions/count_character_occurrences.py
solutions/tests/test_count_character_occurrences.py

Solution 1: Count character occurrences

---

solutions/binary_to_decimal.py
solutions/tests/test_binary_to_decimal.py

adding docstring format after review

---

README.md

Add image to README for better visual appeal

---

solutions/calculate_median.py
solutions/tests/test_calculate_median.py

Updated calculate median soluation after the markdown error

---

solutions/count_vowels.py

refactor count_vowels

---

solutions/calculate_and_classify_bmi.py
solutions/tests/test_calculate_and_classify_bmi.py

---
solution review for - calculating and classifying bmi
---

Function and test file for my second solution 

---

solutions/emoji_sentiment.py
solutions/tests/test_emoji_sentiment.py

adding case insensitive test case

---

.github/PULL_REQUEST_TEMPLATE.md
.vscode/settings.json

Updating the fork with upstream

---

.vscode/settings.json

Added team members' full names to settings.json

---

solutions/README.md
solutions/repeat_characters.py
solutions/tests/test_repeat_characters.py

Solution 2: Repeat characters

---

solutions/count_character_occurrences.py
solutions/tests/test_count_character_occurrences.py

Solution 1: Added comprehensive module-level docstring

---

solutions/sum_odd_numbers.py

Solution 2: Added comprehensive module-level docstring

---

README.md
solutions/calculate_median.py
solutions/capitalize_character.py
solutions/convert_fahrenheit_to_celsius.py
solutions/even_numbers.py
solutions/weight_conversion.py

Partial update to README.md

---

solutions/calculate_median.py
solutions/capitalize_character.py
solutions/convert_fahrenheit_to_celsius.py
solutions/even_numbers.py
solutions/find_max_in_list.py
solutions/weight_conversion.py

Update module docstrings with detailed descriptions

---

solutions/average_of_integers.py
solutions/tests/test_average_of_integers.py

average_of_integers

---

solutions/num_square.py
solutions/tests/test_num_square.py

Add num-square functionality and tests

---

solutions/capitalize_character.py
solutions/count_character_occurrences.py
solutions/tests/test_count_character_occurrences.py

Solution 1: Final_Modified both files for re-approval purposes.

---

solutions/sum_of_squares.py
solutions/tests/test_sum_of_squares.py

Sum of the squares of the numbers in a list

---

solutions/capitalize_character.py
solutions/convert_fahrenheit_to_celsius.py
solutions/even_numbers.py
solutions/find_largest.py
solutions/tests/test_find_largest.py
solutions/weight_conversion.py

solution #3: find the largest in a list

---

solutions/fizzbuzz.py
solutions/tests/test_fizzbuzz.py

fix formating issue
